### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by skela** [gk-brown/Lima#2]
Would be pretty good, since you deleted the old MarkupKit repo :(

**Comment by gk-brown** [comment]
Sorry for the delay in responding - not sure how I missed this.

Could you elaborate a little on what you are looking for? MarkupKit "just worked" with Carthage. I never had to explicitly add support for it. Lima's project structure is nearly identical, so I imagine it should also work.

You could also try using the pre-compiled release binaries. I believe Carthage basically produces the same thing.

**Comment by skela** [comment]
Well I suppose since I didn't see any mention of Carthage in your README, and although I'm not 100% sure, I do believe MarkupKit had a mention about carthage. That coupled with the fact that when I tried to run `carthage update Lima` , it failed.

Tried that command again, with the addition of platform, so:
`carthage update Lima --platform ios`

That worked :+1: 

I also got a bit scared or confused when I read the line in your readme:
"The Lima framework is a universal binary that must be "trimmed" prior to submission to the App Store:"

Making me worry about rejections and the like, don't remember having to trim or anything for MarkupKit. Am I overly worried?

**Comment by gk-brown** [comment]
The MarkupKit README definitely didn't mention Carthage, although it did mention CocoaPods - maybe that's what you are thinking of? In any case, it sounds like you were able to get it working. 🙂

The MarkupKit binaries also needed to be trimmed, although this isn't something you would have needed to do if you were using Carthage. Basically, it just removes the simulator binaries from the framework before the app is uploaded to iTunes Connect.
